# Environment variables.
variables:
  # The Docker host variable is used to connect to the Docker daemon.
  DOCKER_HOST: tcp://docker:2376/
  # GitLab API token, needed to comment on the Merge Request.
  GITLAB_API_TOKEN: $GITLAB_API_TOKEN
  # Discord webhook URL, needed to send a message to the Discord channel.
  DISCORD_WEBHOOK_URL: $DISCORD_WEBHOOK_URL
  # AWS credentials. These are used to login to AWS ECR.
  # The credentials are stored in the GitLab project's variables.
  AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  # ECR repository name.
  # This is the name of the ECR repository where the application image will be pushed.
  AWS_ECR_REPOSITORY_NAME: $AWS_ECR_REPOSITORY_NAME
  # Image prefix.
  # This is the prefix that will be used to tag the application image.
  IMAGE_PREFIX: frontend

# Stages.
# The stages are used to organize the jobs.
# They run in the order they are defined.
stages:
  - test
  - build_and_publish

# Test stage.
#
# This stage runs the tests.
# The pipeline will fail if at least one test fails.
#
# This stage will run when commits are pushed to the develop and main branches.
# It will also run when a merge request is opened against these branches.
test:
  stage: test
  image: node:18.15.0-alpine3.17
  script:
    # Install Dependencies.
    - echo "[Installing Node Dependencies]"
    - yarn install
    # Run tests.
    - echo "[Running Tests]"
    - yarn test
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "main"'
      when: on_success
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: on_success
  after_script:
    # Download curl.
    - echo "[Downloading curl]"
    - apk add --update --no-cache curl
    # Post a comment on the Merge Request with the job result.
    - echo "[Commenting on Merge Request]"
    - |
      NEW_LINE=$'\n'
      JOB_URL="$CI_PROJECT_URL/-/jobs/$CI_JOB_ID"
      if [ "$CI_JOB_STATUS" == "success" ]; then
        BOT_MESSAGE="### :heavy_check_mark: Os Testes Passaram!${NEW_LINE}Boa fera, tu é o(a) cara, $CI_COMMIT_AUTHOR. Veja os [logs do job]($JOB_URL) para mais detalhes. O Merge Request agora está liberado para ser mergeado em \`$CI_MERGE_REQUEST_TARGET_BRANCH_NAME\`."
      else
        BOT_MESSAGE="### :x: Os Testes Falharam!${NEW_LINE}E é tudo culpa do(a) $CI_COMMIT_AUTHOR... Veja os [logs do job]($JOB_URL) para mais detalhes."
      fi
      curl -X POST \
        -H "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
        --form "body=$BOT_MESSAGE" \
        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes"

# Build and publish stage.
#
# This stage builds the application image and publishes it to AWS ECR using Docker.
#
# This stage will run when a commit is pushed to the main branch.
# This stage can also be triggered manually when commits are pushed to the develop branch.
build_and_publish:
  stage: build_and_publish
  image: docker:23.0.3-cli-alpine3.17
  # The service docker:dind is used to run the Docker daemon inside the container.
  # This is needed because the Docker CLI is used to build and push the application image.
  # dind stands for Docker in Docker.
  services:
    - docker:dind
  script:
    # Install AWS CLI.
    - echo "[Installing AWS CLI]"
    - apk add --update --no-cache aws-cli
    # Configure AWS CLI.
    - echo "[Configuring AWS CLI]"
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION
    # Login to AWS ECR.
    - echo "[Logging in to AWS ECR]"
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    # Build the application.
    - echo "[Building the Application Image]"
    - IMAGE_NAME=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_ECR_REPOSITORY_NAME
    - IMAGE_TAG=$IMAGE_PREFIX-$CI_COMMIT_SHA
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    # Push the application to AWS ECR.
    - echo "[Pushing the Application Image to AWS ECR]"
    - docker push $IMAGE_NAME:$IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
  after_script:
    # Download curl.
    - echo "[Downloading curl]"
    - apk add --update --no-cache curl
    # Send a message to the Discord channel.
    - echo "[Sending a message to the Discord channel]"
    - |
      JOB_URL="$CI_PROJECT_URL/-/jobs/$CI_JOB_ID"
      if [ "$CI_JOB_STATUS" == "success" ]; then
        TITLE=":white_check_mark: Build e Publicação (Frontend) - Sucesso!"
        DESCRIPTION="A imagem do frontend foi construída e publicada com sucesso no repositório ECR da AGES! Veja os [logs do job]($JOB_URL) para mais detalhes."
      else
        TITLE=":x: Build e Publicação (Frontend) - Erro!"
        DESCRIPTION="Não foi possível construir e publicar a imagem do frontend no repositório ECR da AGES. Veja os [logs do job]($JOB_URL) para saber o que houve de errado."
      fi
      curl -H "Content-Type: application/json" -X POST -d "{\"embeds\":[{\"title\":\"$TITLE\",\"description\":\"$DESCRIPTION\",\"color\":14177041}]}" $DISCORD_WEBHOOK_URL
